#[derive(PartialEq, Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub enum InstID {
    AUIPC,
    ADDI,
    ANDI,
    BGEU,
    BLT,
    BLTU,
    C_ADD,
    C_ADDI,
    C_ADDIW,
    C_ANDI,
    C_BEQZ,
    C_BNEZ,
    C_J,
    C_JAL,
    C_JR,
    C_SLLI,
    C_SW,
    C_SWSP,
    C_LW,
    C_LWSP,
    C_LI,
    C_MV,
    C_SD,
    C_SUB,
    JAL,
    JALR,
    LD,
    LW,
    SB,
    SD,
    SLLI,
    SRLI,
    SRAI,
    NOP,
    INVALID,
}

pub struct InstInfo<'a> {
    pub name: &'a str,
}

#[allow(non_upper_case_globals)]
pub const inst_info_table: &[InstInfo] = &[
    InstInfo { name: "auipc" },
    InstInfo { name: "addi" },
    InstInfo { name: "andi" },
    InstInfo { name: "bgeu" },
    InstInfo { name: "blt" },
    InstInfo { name: "bltu" },
    InstInfo { name: "c.add" },
    InstInfo { name: "c.addi" },
    InstInfo { name: "c.addiw" },
    InstInfo { name: "c.andi" },
    InstInfo { name: "c.beqz" },
    InstInfo { name: "c.bnez" },
    InstInfo { name: "c.j" },
    InstInfo { name: "c.jal" },
    InstInfo { name: "c.jr" },
    InstInfo { name: "c.slli" },
    InstInfo { name: "c.sw" },
    InstInfo { name: "c.swsp" },
    InstInfo { name: "c.lw" },
    InstInfo { name: "c.lwsp" },
    InstInfo { name: "c.li" },
    InstInfo { name: "c.mv" },
    InstInfo { name: "c.sd" },
    InstInfo { name: "c.sub" },
    InstInfo { name: "jal" },
    InstInfo { name: "jalr" },
    InstInfo { name: "ld" },
    InstInfo { name: "lw" },
    InstInfo { name: "sb" },
    InstInfo { name: "sd" },
    InstInfo { name: "slli" },
    InstInfo { name: "srli" },
    InstInfo { name: "srai" },
    InstInfo { name: "nop" },
    InstInfo { name: "invalid" },
];
